services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault-3
    ports:
      - "8200:8200"
    volumes:
      - vault_data:/vault/data
      - ./vault:/vault
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    command: sh -c "apk add --no-cache jq && /vault/start.sh"
    healthcheck:
      test: ["CMD", "sh", "-c", "vault status && vault kv get secret/database/credentials"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
    restart: unless-stopped
    networks:
      - backend

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-3
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DATABASE
      - CLICKHOUSE_USER
      - CLICKHOUSE_PASSWORD
      - CLICKHOUSE_PORT
      - CLICKHOUSE_HOST
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --query='SELECT 1'"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - backend

  web:
    build: .
    image: zolin17/big-data-3:latest
    container_name: big-data-3
    depends_on:
      clickhouse:
        condition: service_healthy
      vault:
        condition: service_healthy
    command: bash -c "
      python src/preprocess.py &&
      python src/train.py &&
      python src/app.py"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root
    restart: on-failure
    networks:
      - backend

volumes:
  clickhouse_data:
  vault_data:

networks:
  backend:
    driver: bridge
